### ISSUE TITLE
Mismatch between specification and behaviour?

### ISSUE THREAD

**Issue by fabienpe** [dc4eu/vc#70]
[Specifications v2.8](https://github.com/dc4eu/vc/blob/API-Specification/standards/apiv28.md) says that the only required fields in the upload request are `meta`, `document_data` and `document_data_version`.

Example:
```
{
    "document_data": {
        "w38hOqRBEWxFQ1SJ": {
            "oXzd6yiuoKgqUZJx": null
        }
    },
    "document_data_version": "893.85.909",
    "meta": {
        "authentic_source": "ONSS",
        "document_id": "vZ9jQ1uaPIoA5E9Js",
        "document_type": "EHIC",
        "document_version": "31.227.390",
        "real_data": false
    }
}
```

However uploading a request with this limited set of data returns a validation error saying that `identities` and `document_display` are required:
```
{
  "error": {
    "title": "validation_error",
    "details": [
      {
        "field": "identities",
        "namespace": "identities",
        "type": "slice",
        "validation": "required",
        "validationParam": "",
        "value": null
      },
      {
        "field": "document_display",
        "namespace": "document_display",
        "type": "ptr",
        "validation": "required",
        "validationParam": "",
        "value": null
      }
    ]
  }
}
```

After adding an identity and a `document_display`, with required information only, I get a `internal_server_error` message:

```
{
    "document_data": {
        "w38hOqRBEWxFQ1SJ": {
            "oXzd6yiuoKgqUZJx": null
        }
    },
    "identities": [
        {
            "authentic_source_person_id": "AcLr7h5",
            "birth_date": "2974-09-20",
            "family_name": "Kallaste",
            "given_name": "Arkadiusz",
            "schema": {
                "name": "RO"
            }
        }
    ],
    "document_display": {
        "description_structured": {
            "en": {
                "en": "European Health Insurance Card"
            }
        },
        "type": "X1uLdqWJPY",
        "version": "848.484.712"
    },
    "document_data_version": "893.85.909",
    "meta": {
        "authentic_source": "ONSS",
        "document_id": "vZ9jQ1uaPIoA5E9Js",
        "document_type": "EHIC",
        "document_version": "31.227.390",
        "real_data": false
    }
}
```

I'm running `docker.sunet.se/dc4eu/apigw:latest` `sha256:86501d0238553b509fe8780ef6749d31e937bf0d903476921610cd73266af03d` created `2024-07-19T12:56:59.73451228Z`

**Comment by masv3971** [comment]
This should be fixed, https://github.com/dc4eu/vc/commit/3d60ea909881ba0c967a8b0a8abdde3547e14d9c.

Download the latest version of docker.sunet.se/dc4eu/apigw:apiv28 and try it.

**Comment by rappelarsson** [comment]
Hi,

I still have the problem of `500 internal server error` when leaving out the `collect` object, I am using docker.sunet.se/dc4eu/apigw:0.5.4.
